# fly.toml app configuration file generated for azerothcore-mysql on 2025-08-22T17:39:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'azerothcore-mysql'
primary_region = 'fra'
org = 'azerothcore'

[build]
  image = 'mysql:8.4'

[[mounts]]
  source = 'mysql_data'
  destination = '/var/lib/mysql'

[http_service]
  internal_port = 3306
  force_https = true
  auto_stop_machines=false
  auto_start_machines=false
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = "tcp"
  internal_port = 3306
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 3306

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
