#!/usr/bin/env python3
"""
Unique-Equipped Family Generator

Closes a dupe that the item upgrade system would otherwise open.

Player::CanEquipUniqueItem enforces ITEM_FLAG_UNIQUE_EQUIPPABLE by *entry ID*:

    if (itemProto->HasFlag(ITEM_FLAG_UNIQUE_EQUIPPABLE))
        if (HasItemOrGemWithIdEquipped(itemProto->ItemId, 1, except_slot))
            return EQUIP_ERR_ITEM_UNIQUE_EQUIPABLE;      // Player.cpp:13975-13979

An upgraded variant has a different entry, so base + variant of the same unique
trinket would both be equippable -- two copies of an item designed to be worn
once.  The second check in that function is family-based:

    HasItemOrGemWithLimitCategoryEquipped(itemProto->ItemLimitCategory, ...)

...and counts every equipped item sharing the category (PlayerStorage.cpp:769),
so giving a base item and all its variants one shared category with Quantity = 1
restores the intended behaviour.

Category IDs are allocated sequentially in item-entry order.  Deriving them from
the item entry would be preferable -- ids would then be stable no matter how the
item set changed -- but item_template.ItemLimitCategory is a signed SMALLINT and
entries reach ~70k, so they simply do not fit.  See ILC_BASE below for what that
costs and how to avoid paying it.

Run this BEFORE tools/gen_item_variants.py.  Variants inherit ItemLimitCategory
from their base row via INSERT ... SELECT *, and the generator's exclusion of
unique items is written as "unique AND ItemLimitCategory = 0" -- so once these
items have a category they are picked up automatically.

Usage:
    python tools/gen_item_limit_categories.py            # write the SQL file
    python tools/gen_item_limit_categories.py --dry-run  # summary only
    python tools/gen_item_limit_categories.py --stdout   # print SQL
"""

import argparse
import datetime
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO_ROOT, "modules", "world_of_alonecraft", "dbc"))
import config  # noqa: E402

MODULE_SQL = os.path.join(
    REPO_ROOT, "modules", "world_of_alonecraft", "data", "sql", "db-world"
)

ITEM_FLAG_UNIQUE_EQUIPPABLE = 0x00080000

# item_template.ItemLimitCategory is a SIGNED SMALLINT, so ids must fit in
# 32767.  That rules out deriving the id from the item entry (entries reach
# ~70k), which is what the docstring above would otherwise prefer -- ids are
# therefore allocated sequentially from ILC_BASE in item-entry order.
#
# Consequence worth knowing: the mapping is stable only while the underlying
# item set is.  If an item ever enters or leaves scope, every id after it
# shifts.  Always regenerate the variants in the same pass so base items and
# their variants never end up carrying categories from different generations --
# a mismatch would silently reopen the dupe this file exists to close.
#
# Retail ids stop at 85, so 1000+ is clear.
ILC_BASE = 1000

# Variants live at/above this entry; they inherit their base item's category
# rather than getting one of their own.
VARIANT_ENTRY_BASE = 1_000_000

# Every retail row carries this locale mask.
NAME_LANG_MASK = 16712190


def get_db_connection():
    import mysql.connector
    return mysql.connector.connect(
        host=config.MYSQL_HOST,
        user=config.MYSQL_USER,
        password=config.MYSQL_PASS,
        database=config.MYSQL_DB,
    )


def fetch_unique_items(conn):
    """Unique-equipped items in variant scope that have no limit category yet."""
    cur = conn.cursor(dictionary=True)
    cur.execute(
        """
        SELECT entry, name, Quality, InventoryType
        FROM item_template
        WHERE Flags & %s
          AND ItemLimitCategory = 0
          AND Quality BETWEEN 2 AND 5
          AND InventoryType NOT IN (0, 24, 27, 28)
          AND class IN (2, 4)
          AND entry < %s
        ORDER BY entry
        """,
        (ITEM_FLAG_UNIQUE_EQUIPPABLE, VARIANT_ENTRY_BASE),
    )
    rows = cur.fetchall()
    cur.close()
    return rows


def sql_str(value):
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def format_sql(items):
    L = []
    A = L.append
    A("-- ==========================================================================")
    A("-- Unique-Equipped Families -- auto-generated by tools/gen_item_limit_categories.py")
    A("-- ==========================================================================")
    A("--")
    A(f"-- {len(items)} synthetic ItemLimitCategory rows, ids {ILC_BASE}..{ILC_BASE + len(items) - 1}.")
    A("--")
    A("-- ITEM_FLAG_UNIQUE_EQUIPPABLE is enforced by entry id (Player.cpp:13978), so")
    A("-- an upgraded variant would be equippable alongside its own base item.")
    A("-- A shared limit category with Quantity = 1 is the family-based check that")
    A("-- does cover variants (PlayerStorage.cpp:769).")
    A("--")
    A("-- Must be applied BEFORE regenerating variants: the variant generator skips")
    A("-- unique items only while ItemLimitCategory = 0, and variants inherit the")
    A("-- category from their base row.")
    A("")
    A(f"DELETE FROM `itemlimitcategory_dbc` WHERE `ID` >= {ILC_BASE};")
    A("")

    A("-- -- categories ------------------------------------------------------")
    ids = {it["entry"]: ILC_BASE + n for n, it in enumerate(items)}
    rows = [
        "({}, {}, {}, 1, 0)".format(ids[i["entry"]], sql_str(i["name"]), NAME_LANG_MASK)
        for i in items
    ]
    for i in range(0, len(rows), 500):
        A("INSERT INTO `itemlimitcategory_dbc` "
          "(`ID`, `Name_Lang_enUS`, `Name_Lang_Mask`, `Quantity`, `Flags`) VALUES")
        A(",\n".join(rows[i:i + 500]) + ";")
        A("")

    A("-- -- tag the base items ----------------------------------------------")
    A("-- Variants pick this up automatically when they are regenerated.")
    for i in range(0, len(items), 500):
        chunk = items[i:i + 500]
        cases = " ".join(
            f"WHEN {it['entry']} THEN {ids[it['entry']]}" for it in chunk
        )
        entries = ", ".join(str(it["entry"]) for it in chunk)
        A(f"UPDATE `item_template` SET `ItemLimitCategory` = CASE `entry` {cases} END "
          f"WHERE `entry` IN ({entries});")
        A("")

    return "\n".join(L) + "\n"


def next_sql_path():
    today = datetime.date.today().strftime("%Y_%m_%d")
    seq = 0
    while os.path.exists(os.path.join(MODULE_SQL, f"woa_{today}_{seq:02d}.sql")):
        seq += 1
    return os.path.join(MODULE_SQL, f"woa_{today}_{seq:02d}.sql")


def main():
    p = argparse.ArgumentParser(description="Generate unique-equipped families")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--stdout", action="store_true")
    args = p.parse_args()

    conn = get_db_connection()
    items = fetch_unique_items(conn)
    conn.close()

    print(f"Unique-equipped items needing a family: {len(items)}", file=sys.stderr)
    if items:
        by_slot = {}
        for it in items:
            by_slot[it["InventoryType"]] = by_slot.get(it["InventoryType"], 0) + 1
        top = sorted(by_slot.items(), key=lambda kv: -kv[1])[:5]
        print("  by slot: " + ", ".join(f"invtype {k}: {v}" for k, v in top), file=sys.stderr)

    if args.dry_run or not items:
        return

    sql = format_sql(items)
    if args.stdout:
        sys.stdout.write(sql)
        return

    path = next_sql_path()
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(sql)
    print(f"Wrote {path} ({len(sql) / 1024:.0f} KB)", file=sys.stderr)


if __name__ == "__main__":
    main()
