#!/usr/bin/env python3
"""
Upgrade Tool Generator

Emits the 16 consumable "upgrade tools" sold by Artificer Volen, one per target
level (5, 10, ... 80).  Using a tool gives the item-targeting cursor -- the same
interaction as a sharpening stone -- and clicking an item upgrades it to that
tool's level.

Why a vendor item rather than a gossip menu: the price and the shop UI become
plain `npc_vendor` data, so there is no gold handling and no menu code to get
wrong.  The previous gossip implementation's destroy-then-equip swap crashed the
server inside SaveToDB; this design removes that whole surface.

Each tool needs FOUR rows, and all four are mandatory:

  * `alonecraft_spell_dbc` -- the item-targeted spell (Targets = TARGET_FLAG_ITEM,
                              Effect = SPELL_EFFECT_SCRIPT_EFFECT so the script
                              receives GetHitItem()).
  * `item_template`        -- the consumable, spelltrigger 0 (on use).
  * `item_dbc`             -- without it the item_template row is silently
                              discarded at load (ObjectMgr.cpp:3487), and it also
                              feeds the client's Item.dbc so the icon resolves.
  * `spell_script_names`   -- binds the spell to the C++ handler.

Target levels are absolute multiples of 5, which is only true because
gen_item_variants.py snaps them there.  If that ever changes, a per-level tool
stops matching most items' upgrade chains and this design breaks.

Usage:
    python tools/gen_upgrade_tools.py            # write the SQL file
    python tools/gen_upgrade_tools.py --dry-run  # summary only
    python tools/gen_upgrade_tools.py --stdout   # print SQL
"""

import argparse
import datetime
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO_ROOT, "tools"))
sys.path.insert(0, os.path.join(REPO_ROOT, "modules", "world_of_alonecraft", "dbc"))
import config  # noqa: E402
from spell_dbc import SPELL_COLUMNS, load_spell_index  # noqa: E402
import gen_sql  # noqa: E402

MODULE_SQL = os.path.join(
    REPO_ROOT, "modules", "world_of_alonecraft", "data", "sql", "db-world"
)

# ── ID allocation ───────────────────────────────────────────────────────────
# 200000-200525 is already densely used by Alonecraft spells, so the tools take
# a fresh block.  Item entries must stay below the variant band (1,000,000).
SPELL_BASE = 201000
ITEM_BASE = 200100
VENDOR_ENTRY = 200011          # Artificer Volen
SCRIPT_NAME = "spell_item_upgrade_tool"

# ItemDisplayInfo rows of our own, one per tool, so each level gets a distinct
# recoloured icon.  Retail's table ends at 68742, so 69000+ is free.  The rows
# themselves and the icon art are generated by tools/gen_upgrade_icons.py; this
# only has to agree with it about the numbering.
DISPLAY_BASE = 69000

# Cloned for its item-targeting shape: Targets = 16 (TARGET_FLAG_ITEM),
# RangeIndex = 1.  See "Sharpen Blade".  Its EffectImplicitTargetA1 = 0 is NOT
# copied -- see the note where that field is set.
BASE_SPELL = 29453

STEP_SIZE = 5
MAX_LEVEL = 80

SPELL_EFFECT_SCRIPT_EFFECT = 77
TARGET_FLAG_ITEM = 16

# The only implicit target in SpellImplicitTargetInfo::_data with an item object
# type (SpellInfo.cpp:239).  See the comment at its use site.
TARGET_GAMEOBJECT_ITEM_TARGET = 26

# One name per target level.  Ethereal/arcane theme, matching Volen's model and
# the other Alonecraft service NPCs; the material family escalates
# Mote -> Shard -> Prism -> Sigil so tier is legible at a glance in the shop.
TOOL_NAMES = {
    5:  "Flickering Ethereal Mote",
    10: "Dim Ethereal Mote",
    15: "Glimmering Ethereal Mote",
    20: "Radiant Ethereal Mote",
    25: "Fractured Ethereal Shard",
    30: "Lucid Ethereal Shard",
    35: "Gleaming Ethereal Shard",
    40: "Brilliant Ethereal Shard",
    45: "Shifting Nexus Prism",
    50: "Resonant Nexus Prism",
    55: "Coalesced Nexus Prism",
    60: "Refracted Nexus Prism",
    65: "Woven Astral Sigil",
    70: "Ascendant Astral Sigil",
    75: "Transcendent Astral Sigil",
    80: "Eternal Astral Sigil",
}

# Fallback adjective per level, used by gen_item_variants.py only when the tool's
# own adjective is already the first word of the item being upgraded -- otherwise
# you get "Brilliant Brilliant Gold Ring".  Four of the sixteen actually collide
# in the 3.3.5a item set (Gleaming, Brilliant, Woven, Eternal), but every level
# gets one so a future item name cannot reintroduce the problem.
#
# Each must be distinct from ALL sixteen primaries, not merely from its own:
# reusing one would make the level ambiguous, which is the property that lets a
# name be read back as a level.
TOOL_ALT_PREFIX = {
    5:  "Guttering",
    10: "Faded",
    15: "Twinkling",
    20: "Beaming",
    25: "Riven",
    30: "Limpid",
    35: "Burnished",
    40: "Lustrous",
    45: "Wavering",
    50: "Humming",
    55: "Fused",
    60: "Prismatic",
    65: "Threaded",
    70: "Rising",
    75: "Exalted",
    80: "Undying",
}

# Flat per level: a tool's price cannot depend on what you use it on, so the
# quality term from the old gossip pricing is gone.
#
# The coefficient is fitted so the curve lands on what a class trainer charges to
# teach a spell at the same level -- an upgrade should read as a routine levelling
# expense, not a savings goal.  Median trainer cost against 1.75 * L^2.6:
#
#     level      10      20      30      40      50      60       70       80
#     trainer   500   4,000   8,000  18,000  30,000  46,000  100,000  180,000
#     tool      696   4,223  12,121  25,609  45,746  73,490  109,721  155,264
#
# Close at both ends and somewhat high through the middle, where the trainer
# curve dips.  It was 21.0 -- twelve times this -- which put a level-80 reforge
# at 186g and made the whole system feel like an endgame gold sink.
def tool_price(level):
    copper = 1.75 * (level ** 2.6)
    return max(100, int(round(copper / 100.0)) * 100)


def spell_id(level):
    return SPELL_BASE + (level // STEP_SIZE) - 1


def item_id(level):
    return ITEM_BASE + (level // STEP_SIZE) - 1


def display_id(level):
    return DISPLAY_BASE + (level // STEP_SIZE) - 1


def sql_str(value):
    return "'" + str(value).replace("\\", "\\\\").replace("'", "''") + "'"


def build_spell_rows(dbc_index):
    """One alonecraft_spell_dbc row per tool, cloned from BASE_SPELL."""
    base = dbc_index.get(BASE_SPELL)
    if not base:
        sys.exit(f"ERROR: base spell {BASE_SPELL} not found in Spell.dbc")

    rows = []
    for level, name in sorted(TOOL_NAMES.items()):
        row = dict(base)
        row["ID"] = spell_id(level)
        row["SpellName0"] = name

        # Item targeting: the cursor becomes an item picker and the script
        # receives the clicked item via GetHitItem().
        #
        # Both fields are load-bearing and they do different jobs.  Targets tells
        # the CLIENT to offer the item cursor.  EffectImplicitTargetA1 is what
        # actually puts the clicked item in the server's target list -- and it
        # cannot be left at 0 here, because SPELL_EFFECT_SCRIPT_EFFECT is
        # {EFFECT_IMPLICIT_TARGET_NONE, TARGET_OBJECT_TYPE_NONE} in
        # SpellEffectInfo::_data (SpellInfo.cpp:668), so
        # Spell::SelectEffectTypeImplicitTargets returns immediately
        # (Spell.cpp:1996) and no target is ever added.  That shipped once: the
        # tool cast, played its animation, consumed the charge and did nothing.
        #
        # Sharpen Blade gets away with 0 only because ENCHANT_ITEM_TEMPORARY is
        # declared {EXPLICIT, ITEM} in the same table.  Do not copy its value.
        row["Targets"] = TARGET_FLAG_ITEM
        row["Effect1"] = SPELL_EFFECT_SCRIPT_EFFECT
        row["EffectImplicitTargetA1"] = TARGET_GAMEOBJECT_ITEM_TARGET
        row["Effect2"] = 0
        row["Effect3"] = 0

        # The base spell restricts to sharpenable weapons; these apply to any
        # equippable item, so drop the restriction entirely.
        row["EquippedItemClass"] = -1
        row["EquippedItemSubClassMask"] = 0
        row["EquippedItemInventoryTypeMask"] = 0

        # Carry the target level in the spell itself, so the C++ never needs a
        # hardcoded id-to-level table.
        row["MaximumLevel"] = level

        desc = (f"Reforges an item to level {level}, scaling its statistics to "
                f"match. The item must be one you could otherwise upgrade.")
        for col in ("SpellDescription0", "SpellToolTip0"):
            if col in row:
                row[col] = desc

        rows.append((level, row))
    return rows


def format_sql(spell_rows, field_names):
    L = []
    A = L.append
    A("-- ==========================================================================")
    A("-- Item Upgrade Tools -- auto-generated by tools/gen_upgrade_tools.py")
    A("-- ==========================================================================")
    A("--")
    A(f"-- {len(spell_rows)} consumables sold by Artificer Volen ({VENDOR_ENTRY}), one per")
    A("-- target level.  Using one gives the item-targeting cursor; clicking an")
    A("-- item upgrades it to that tool's level.")
    A("--")
    A("-- Target levels are absolute multiples of 5.  That only holds because")
    A("-- gen_item_variants.py snaps them there -- with relative steps a level-23")
    A("-- item's chain runs 28/33/38 and a per-level tool would never match it.")
    A("--")
    A("-- Every tool needs an item_dbc row as well as item_template: without one")
    A("-- the template is silently discarded at load (ObjectMgr.cpp:3487).")
    A("")

    lo, hi = spell_id(5), spell_id(MAX_LEVEL)
    ilo, ihi = item_id(5), item_id(MAX_LEVEL)
    A(f"DELETE FROM `alonecraft_spell_dbc` WHERE `ID` BETWEEN {lo} AND {hi};")
    A(f"DELETE FROM `spell_script_names`  WHERE `spell_id` BETWEEN {lo} AND {hi};")
    A(f"DELETE FROM `npc_vendor`          WHERE `entry` = {VENDOR_ENTRY};")
    A(f"DELETE FROM `item_template`       WHERE `entry` BETWEEN {ilo} AND {ihi};")
    A(f"DELETE FROM `item_dbc`            WHERE `ID`    BETWEEN {ilo} AND {ihi};")
    A("")

    A("-- -- spells -----------------------------------------------------------")
    for level, row in spell_rows:
        # Note the argument order: format_sql_value(value, col_name).
        values = ", ".join(gen_sql.format_sql_value(row.get(c, 0), c) for c in field_names)
        A(f"-- {TOOL_NAMES[level]} (level {level})")
        A(f"INSERT INTO `alonecraft_spell_dbc` VALUES ({values});")
    A("")

    A("-- -- script binding ---------------------------------------------------")
    A("INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES")
    A(",\n".join(f"({spell_id(l)}, {sql_str(SCRIPT_NAME)})" for l in sorted(TOOL_NAMES)) + ";")
    A("")

    A("-- -- items ------------------------------------------------------------")
    A("-- class 15 / subclass 0 = Miscellaneous/Junk, so they stack and vendor")
    A("-- cleanly.  spelltrigger 0 = on use; spellcharges -1 = consumed on use.")
    A("INSERT INTO `item_template`")
    A("  (`entry`, `class`, `subclass`, `name`, `displayid`, `Quality`, `Flags`,")
    A("   `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `stackable`,")
    A("   `Material`, `sheath`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`,")
    A("   `bonding`, `Description`, `RequiredLevel`, `ItemLevel`)")
    A("VALUES")
    item_rows = []
    for level in sorted(TOOL_NAMES):
        price = tool_price(level)
        desc = f"Reforges an item to level {level}."
        item_rows.append(
            "({}, 15, 0, {}, {}, 3, 0, 1, {}, {}, 0, 20, 0, 0, {}, 0, -1, 0, {}, {}, {})".format(
                item_id(level), sql_str(TOOL_NAMES[level]), display_id(level),
                price, price // 5,
                # RequiredLevel = the level it reforges to, so the red "Requires
                # Level N" line and Player::CanUseItem refuse the wrong tool
                # before any spell is cast -- not just the script's CheckCast,
                # which only speaks up after the purchase.
                spell_id(level), sql_str(desc), level, level)
        )
    A(",\n".join(item_rows) + ";")
    A("")

    A("-- -- item_dbc (mandatory; also feeds the client's patched Item.dbc) ----")
    A("INSERT INTO `item_dbc`")
    A("  (`ID`, `ClassID`, `SubclassID`, `Sound_Override_Subclassid`, `Material`,")
    A("   `DisplayInfoID`, `InventoryType`, `SheatheType`) VALUES")
    A(",\n".join(f"({item_id(l)}, 15, 0, -1, 0, {display_id(l)}, 0, 0)"
                 for l in sorted(TOOL_NAMES)) + ";")
    A("")

    A("-- -- vendor stock -----------------------------------------------------")
    A("-- maxcount 0 = unlimited stock, no restock timer.")
    A("INSERT INTO `npc_vendor` (`entry`, `slot`, `item`, `maxcount`, `incrtime`, `ExtendedCost`) VALUES")
    A(",\n".join(f"({VENDOR_ENTRY}, {n}, {item_id(l)}, 0, 0, 0)"
                 for n, l in enumerate(sorted(TOOL_NAMES), start=1)) + ";")
    A("")

    A("-- -- make Volen an actual vendor --------------------------------------")
    A("-- npcflag 128 = UNIT_NPC_FLAG_VENDOR (was 1 = GOSSIP).")
    A(f"UPDATE `creature_template` SET `npcflag` = 128, `ScriptName` = '' WHERE `entry` = {VENDOR_ENTRY};")
    return "\n".join(L) + "\n"


def next_sql_path():
    today = datetime.date.today().strftime("%Y_%m_%d")
    seq = 0
    while os.path.exists(os.path.join(MODULE_SQL, f"woa_{today}_{seq:02d}.sql")):
        seq += 1
    return os.path.join(MODULE_SQL, f"woa_{today}_{seq:02d}.sql")


def main():
    p = argparse.ArgumentParser(description="Generate item upgrade tools")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--stdout", action="store_true")
    args = p.parse_args()

    dbc_index = load_spell_index(config.BASE_DBC_PATH)
    field_names = list(SPELL_COLUMNS)
    spell_rows = build_spell_rows(dbc_index)

    print(f"Tools: {len(spell_rows)}", file=sys.stderr)
    for level, _ in spell_rows:
        print("  L%-3d %-28s spell %d  item %d  %6d c  (%dg)"
              % (level, TOOL_NAMES[level], spell_id(level), item_id(level),
                 tool_price(level), tool_price(level) // 10000), file=sys.stderr)

    if args.dry_run:
        return

    sql = format_sql(spell_rows, field_names)
    if args.stdout:
        sys.stdout.write(sql)
        return

    path = next_sql_path()
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(sql)
    print(f"Wrote {path} ({len(sql) / 1024:.0f} KB)", file=sys.stderr)


if __name__ == "__main__":
    main()
