#!/usr/bin/env python3
"""
Alonecraft New Spell Script Scaffolder

Generates a C++ spell script, SQL registration file, and updates MP_loader.cpp
from a single command -- ensuring all three registration points stay consistent.

Usage:
    python tools/new_spell_script.py --name spell_example --spell-ids 200100 --type SpellScript --addsc AddSC_example
    python tools/new_spell_script.py --name aura_example  --spell-ids 200101,200102 --type AuraScript --addsc AddSC_example_aura

Options:
    --name        Script name (used in SpellScriptLoader and spell_script_names)
    --spell-ids   Comma-separated spell IDs (negative = all ranks)
    --type        Script type: SpellScript or AuraScript (default: SpellScript)
    --addsc       AddSC_* function name (default: derived from --name)
    --cpp-file    Output .cpp filename (default: derived from --name)
    --dry-run     Show what would be generated without writing files
"""

import argparse
import datetime
import glob
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE_SRC = os.path.join(REPO_ROOT, "modules", "world_of_alonecraft", "src")
MODULE_SQL = os.path.join(REPO_ROOT, "modules", "world_of_alonecraft", "data", "sql", "db-world")
LOADER_FILE = os.path.join(MODULE_SRC, "MP_loader.cpp")


SPELL_SCRIPT_TEMPLATE = '''#include "ScriptMgr.h"
#include "SpellScript.h"
#include "SpellAuraEffects.h"
#include "Unit.h"

class {class_name} : public SpellScript
{{
    PrepareSpellScript({class_name});

    void HandleOnHit()
    {{
        Unit* caster = GetCaster();
        Unit* target = GetHitUnit();

        if (!caster || !target)
            return;

        // TODO: Implement spell effect
    }}

    void Register() override
    {{
        OnHit += SpellHitFn({class_name}::HandleOnHit);
    }}
}};

class {loader_class} : public SpellScriptLoader
{{
public:
    {loader_class}() : SpellScriptLoader("{script_name}") {{ }}

    SpellScript* GetSpellScript() const override
    {{
        return new {class_name}();
    }}
}};

void {addsc_func}()
{{
    new {loader_class}();
}}
'''

AURA_SCRIPT_TEMPLATE = '''#include "ScriptMgr.h"
#include "SpellScript.h"
#include "SpellAuraEffects.h"
#include "Unit.h"

class {class_name} : public AuraScript
{{
    PrepareAuraScript({class_name});

    bool CheckProc(ProcEventInfo& eventInfo)
    {{
        Unit* actor = eventInfo.GetActor();
        if (!actor)
            return false;

        // TODO: Implement proc check
        return true;
    }}

    void Register() override
    {{
        DoCheckProc += AuraCheckProcFn({class_name}::CheckProc);
    }}
}};

class {loader_class} : public SpellScriptLoader
{{
public:
    {loader_class}() : SpellScriptLoader("{script_name}") {{ }}

    AuraScript* GetAuraScript() const override
    {{
        return new {class_name}();
    }}
}};

void {addsc_func}()
{{
    new {loader_class}();
}}
'''


def get_next_sql_sequence(sql_dir):
    """Find the next YYYY_MM_DD_XX.sql sequence number for today."""
    today = datetime.date.today().strftime("%Y_%m_%d")
    existing = glob.glob(os.path.join(sql_dir, f"{today}_*.sql"))
    max_seq = -1
    for f in existing:
        basename = os.path.basename(f)
        match = re.match(r"\d{4}_\d{2}_\d{2}_(\d+)\.sql", basename)
        if match:
            max_seq = max(max_seq, int(match.group(1)))
    return today, max_seq + 1


def generate_sql(script_name, spell_ids, today, seq):
    """Generate idempotent SQL for spell_script_names registration."""
    filename = f"{today}_{seq:02d}.sql"

    lines = []
    lines.append(f"-- Alonecraft: Register {script_name}")
    lines.append(f"-- Auto-generated by new_spell_script.py on {today.replace('_', '-')}")
    lines.append("")
    lines.append(f"DELETE FROM `spell_script_names` WHERE `ScriptName` = '{script_name}';")
    lines.append(f"INSERT INTO `spell_script_names` (`spell_id`, `ScriptName`) VALUES")

    value_lines = []
    for sid in spell_ids:
        value_lines.append(f"    ({sid}, '{script_name}')")
    lines.append(",\n".join(value_lines) + ";")

    return filename, "\n".join(lines) + "\n"


def update_loader(addsc_func, dry_run=False):
    """Add forward declaration and call to MP_loader.cpp."""
    with open(LOADER_FILE, "r", encoding="utf-8") as f:
        content = f.read()

    decl_line = f"void {addsc_func}();\n"
    call_line = f"    {addsc_func}();\n"

    # Check if already present
    if addsc_func in content:
        print(f"  WARNING: {addsc_func} already exists in MP_loader.cpp -- skipping update")
        return False

    # Insert declaration before the "// Add all" comment
    marker = "// Add all"
    if marker not in content:
        print("  ERROR: Could not find '// Add all' marker in MP_loader.cpp")
        return False

    content = content.replace(marker, decl_line + marker)

    # Insert call before the closing brace of Addworld_of_alonecraftScripts()
    # Find the last line before the closing }
    func_pattern = re.compile(r"(void Addworld_of_alonecraftScripts\(\)\s*\{.*?)(^\})", re.DOTALL | re.MULTILINE)
    match = func_pattern.search(content)
    if not match:
        print("  ERROR: Could not find Addworld_of_alonecraftScripts() closing brace")
        return False

    content = content[:match.start(2)] + call_line + content[match.start(2):]

    if not dry_run:
        with open(LOADER_FILE, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)

    return True


def main():
    parser = argparse.ArgumentParser(description="Alonecraft New Spell Script Scaffolder")
    parser.add_argument("--name", required=True, help="Script name for SpellScriptLoader")
    parser.add_argument("--spell-ids", required=True, help="Comma-separated spell IDs")
    parser.add_argument("--type", default="SpellScript", choices=["SpellScript", "AuraScript"],
                        help="Script base class")
    parser.add_argument("--addsc", help="AddSC_* function name (default: AddSC_<name>)")
    parser.add_argument("--cpp-file", help="Output .cpp filename (default: <Name>.cpp)")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing files")
    args = parser.parse_args()

    script_name = args.name
    spell_ids = [int(x.strip()) for x in args.spell_ids.split(",")]
    script_type = args.type
    addsc_func = args.addsc or f"AddSC_{script_name}"

    # Derive class names
    class_name = script_name  # e.g., "spell_example"
    loader_class = f"{script_name}_loader"

    # Derive cpp filename from script name (CamelCase)
    if args.cpp_file:
        cpp_filename = args.cpp_file
    else:
        # Convert snake_case to CamelCase for filename
        parts = script_name.replace("spell_", "").replace("aura_", "").split("_")
        cpp_filename = "".join(p.capitalize() for p in parts) + ".cpp"

    print()
    print("=" * 60)
    print("  Alonecraft New Spell Script Scaffolder")
    print("=" * 60)
    print()
    print(f"  Script name:    {script_name}")
    print(f"  Script type:    {script_type}")
    print(f"  Spell IDs:      {spell_ids}")
    print(f"  AddSC function: {addsc_func}()")
    print(f"  C++ file:       {cpp_filename}")
    print()

    # Generate C++ file
    template = SPELL_SCRIPT_TEMPLATE if script_type == "SpellScript" else AURA_SCRIPT_TEMPLATE
    cpp_content = template.format(
        class_name=class_name,
        loader_class=loader_class,
        script_name=script_name,
        addsc_func=addsc_func,
    )

    cpp_path = os.path.join(MODULE_SRC, cpp_filename)
    if os.path.exists(cpp_path):
        print(f"  ERROR: {cpp_filename} already exists in {MODULE_SRC}")
        return 1

    # Generate SQL file
    today, seq = get_next_sql_sequence(MODULE_SQL)
    sql_filename, sql_content = generate_sql(script_name, spell_ids, today, seq)
    sql_path = os.path.join(MODULE_SQL, sql_filename)

    if args.dry_run:
        print("  [DRY RUN] Would create:")
        print(f"    {cpp_path}")
        print(f"    {sql_path}")
        print(f"    Update MP_loader.cpp with {addsc_func}()")
        print()
        print("  --- C++ ---")
        print(cpp_content)
        print("  --- SQL ---")
        print(sql_content)
        return 0

    # Write C++ file
    with open(cpp_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(cpp_content)
    print(f"  Created: {cpp_path}")

    # Write SQL file
    with open(sql_path, "w", encoding="utf-8", newline="\n") as f:
        f.write(sql_content)
    print(f"  Created: {sql_path}")

    # Update MP_loader.cpp
    if update_loader(addsc_func):
        print(f"  Updated: {LOADER_FILE}")
        print(f"    Added declaration: void {addsc_func}();")
        print(f"    Added call: {addsc_func}();")

    print()
    print("  Done! Next steps:")
    print(f"  1. Implement the spell logic in {cpp_filename}")
    print(f"  2. Run: python tools/verify_scripts.py  (confirm consistency)")
    print(f"  3. Run: build_and_run.bat")
    print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
